# A metric is a computational expression of numerical data (facts or other metrics).
# Use MAQL to create reusable multidimensional queries that combine multiple facts and attributes.
# Read more about MAQL:
# https://www.gooddata.com/developers/cloud-native/doc/cloud/create-metrics/maql/

type: metric
id: product_rating

title: Product Rating

maql: SELECT AVG({fact/rating})
format: "#,##0.0"
